version: 2.1

jobs:
  build_and_test:
    docker:
      - image: python:3.8-bullseye

    steps:
      - checkout

      - run:
          name: List all files
          command: ls -al

      - run:
          name: Test presence of python3
          command: |
            python3 --version

      - run:
          name: Install poetry
          command: |
            pip --verbose install poetry==1.8.5

      - run:
          name: Install dependencies
          command: |
            poetry config virtualenvs.create false
            poetry install --verbose --no-ansi

      - run:
          name: Lint and test code
          command: make clean poetry-check lint test coverage

workflows:
  test_my_app:
    jobs:
      - build_and_test
